# E0023

The body of this try expression never raises any error.

## Erroneous example

```moonbit
///|
fn main {
  println("Hello, world!") catch { // `try` is omitted here
    _ => println("Error")
  }
  try {
    println("Hello, ")
    println("world!")
  } catch {
    _ => println("Error in try block")
  }
}
```

## Suggestion

Remove the `try` expression:

```moonbit
///|
fn main {
  println("Hello, world!")
}
```
